services:
  - type: web
    name: smart-ride-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    dockerContext: .
    buildArgs:
      - key: CACHE_BUST
        value: "3"

  - type: web
    name: smart-ride-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: smart-ride-backend
          envVarKey: RENDER_EXTERNAL_URL
