services:
  - type: web
    name: smart-ride-backend
    env: docker
    plan: free

  - type: static
    name: smart-ride-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: smart-ride-backend
          envVarKey: RENDER_EXTERNAL_URL
