services:
  - type: web
    name: smart-ride-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    dockerContext: .

  - type: web
    name: smart-ride-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://smart-ride-backend-jkeu.onrender.com/api/:splat
    envVars:
      - key: VITE_API_BASE_URL
        value: ""
